# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_add_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leCommand = QtWidgets.QLineEdit(self.centralwidget)
        self.leCommand.setGeometry(QtCore.QRect(300, 510, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leCommand.setFont(font)
        self.leCommand.setObjectName("leCommand")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 510, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btCommand = QtWidgets.QPushButton(self.centralwidget)
        self.btCommand.setGeometry(QtCore.QRect(640, 510, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btCommand.setFont(font)
        self.btCommand.setObjectName("btCommand")
        self.pteData = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pteData.setGeometry(QtCore.QRect(10, 10, 811, 491))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pteData.setFont(font)
        self.pteData.setReadOnly(True)
        self.pteData.setObjectName("pteData")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Задача 1 необязательная: чат-бот с локальным хранилищем"))
        self.label.setText(_translate("MainWindow", "Введите команду:"))
        self.btCommand.setText(_translate("MainWindow", "Выполнить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
